name: build android apk
on: 
  push:
    branches:
      - main

jobs:
  android-job:
      runs-on: ubuntu-latest
      steps:
        - name: print a welcome messages
          run: echo "this is new build for android apk"
